//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_ATTRIB_DATA_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBS_ATTRIB_DATA_TYPES()
        {
            this.OBS_FORM_ATTRIBS = new HashSet<OBS_FORM_ATTRIBS>();
        }
    
        public short obs_attrib_data_type_id { get; set; }
        public string obs_attrib_data_type_name { get; set; }
        public string obs_attrib_data_type_len_yn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBS_FORM_ATTRIBS> OBS_FORM_ATTRIBS { get; set; }
    }
}
