//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_ANS_TYPE
    {
        public short obs_ans_type_id { get; set; }
        public string obs_ans_type_name { get; set; }
        public string obs_ans_type_desc { get; set; }
        public string obs_ans_type_has_fxd_ans_yn { get; set; }
        public string obs_ans_type_free_text_yn { get; set; }
        public string obs_ans_type_comment_mand_yn { get; set; }
        public string obs_ans_type_api_tag_val { get; set; }
    }
}
