//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_INST_EVENT_LOG
    {
        public long obs_inst_event_log_id { get; set; }
        public short obs_event_type_id { get; set; }
        public long obs_inst_id { get; set; }
        public Nullable<long> obs_cfi_id { get; set; }
        public string obs_inst_event_text { get; set; }
    
        public virtual OBS_COLLECT_FORM_INST OBS_COLLECT_FORM_INST { get; set; }
        public virtual OBS_EVENT_TYPE OBS_EVENT_TYPE { get; set; }
        public virtual OBS_INST OBS_INST { get; set; }
        public virtual OBS_RVW_FORM_INST OBS_RVW_FORM_INST { get; set; }
    }
}
